name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.x
          check-latest: true

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run ng -- deploy --base-href=/coffee-ratio/ --name="itsjoshpark" --email="jpark@duck.com" --no-silent
